/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import negocio.ClasesOrdenadoras.ComparaPorEdad;
import negocio.ClasesOrdenadoras.ComparaPorGenero;
import negocio.ClasesOrdenadoras.ComparaPorNombreYApe;
import negocio.GestorEncuestas;

/**
 *
 * @author Mosqueteros
 */
public class VentanaListadosOrdenados extends javax.swing.JFrame {

    private VentanaPrincipal ventPrin;
    private GestorEncuestas gestor;
    
    
    public VentanaListadosOrdenados(VentanaPrincipal vp, GestorEncuestas g) {
        ventPrin=vp;
        gestor=g;
        initComponents();
    }
    
    public void limpiarPantalla(){
        btnGroupOrdenarPor.clearSelection();
        txtAListado.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupOrdenarPor = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        optApellidoYNombre = new javax.swing.JRadioButton();
        optEdad = new javax.swing.JRadioButton();
        optGenero = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAListado = new javax.swing.JTextArea();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Orden por: ");

        btnGroupOrdenarPor.add(optApellidoYNombre);
        optApellidoYNombre.setText("Apellido y Nombre");
        optApellidoYNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optApellidoYNombreActionPerformed(evt);
            }
        });

        btnGroupOrdenarPor.add(optEdad);
        optEdad.setText("Edad");
        optEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optEdadActionPerformed(evt);
            }
        });

        btnGroupOrdenarPor.add(optGenero);
        optGenero.setText("Genero");
        optGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optGeneroActionPerformed(evt);
            }
        });

        txtAListado.setColumns(20);
        txtAListado.setRows(5);
        jScrollPane1.setViewportView(txtAListado);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnLimpiar)
                .addGap(62, 62, 62)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(234, 234, 234))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optGenero)
                    .addComponent(optEdad)
                    .addComponent(optApellidoYNombre))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(optApellidoYNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optEdad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optGenero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnSalir))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        ventPrin.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarPantalla();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void optApellidoYNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optApellidoYNombreActionPerformed
        gestor.ordenarColeccion(new ComparaPorNombreYApe());
        String res=gestor.mostrarEncuestas();
        txtAListado.setText(res);
    }//GEN-LAST:event_optApellidoYNombreActionPerformed

    private void optEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optEdadActionPerformed
        gestor.ordenarColeccion(new ComparaPorEdad());
        String res=gestor.mostrarEncuestas();
        txtAListado.setText(res);
    }//GEN-LAST:event_optEdadActionPerformed

    private void optGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optGeneroActionPerformed
        gestor.ordenarColeccion(new ComparaPorGenero());
        String res=gestor.mostrarEncuestas();
        txtAListado.setText(res);
    }//GEN-LAST:event_optGeneroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupOrdenarPor;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton optApellidoYNombre;
    private javax.swing.JRadioButton optEdad;
    private javax.swing.JRadioButton optGenero;
    private javax.swing.JTextArea txtAListado;
    // End of variables declaration//GEN-END:variables
}
